#! /usr/bin/python3
""" Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be: 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89.
Write a function which returns the sum of the even numbers in the Fibonacci series for N terms."""


def find_sum_of_even_numbers_fibonacci(num):
    """" Function to Find sum of Fibonacci numbers"""
    i = 0
    sum_of_even = 0
    num1 = 1
    num2 = 0
    while i < num:
        next_num = num1+num2
        num2 = num1
        num1 = next_num
        i = i+1
        if next_num % 2 == 0:
            sum_of_even = sum_of_even+next_num
#        print(i, "values : ", c)
    return sum_of_even


if __name__ == '__main__':
    print(find_sum_of_even_numbers_fibonacci(5))
